name: Linux Emscripten

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  BareBones:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Install Required Toolchain
        run: |
          sudo apt update
          sudo apt install -y python3 python3-pip python-is-python3 libglfw3 clang ccache

          git submodule update --init --recursive 
          
          ./third-party/emsdk/emsdk install latest
          ./third-party/emsdk/emsdk activate latest

      - uses: actions/cache@v2
        id: cache
        with:
          path: /tmp/ccache
          key: ${{ runner.os }}-emscripten-${{ hashFiles('**/*.manifest') }}

      - name: Generate Build Files
        run: |
          source ./third-party/emsdk/emsdk_env.sh

          mkdir ./out/
          cp ./.ide/GN/linux/emscripten/args.gn ./out/args.gn

          chmod +x ./tools/linux/*

          ./tools/linux/gn gen out

      - name: Build BareBones
        run: |
          source ./third-party/emsdk/emsdk_env.sh

          ./tools/linux/ninja -C out BareBones
